# Assignment

<font face='georgia'>
    
   <h4><strong>What does tf-idf mean?</strong></h4>

   <p>    
Tf-idf stands for <em>term frequency-inverse document frequency</em>, and the tf-idf weight is a weight often used in information retrieval and text mining. This weight is a statistical measure used to evaluate how important a word is to a document in a collection or corpus. The importance increases proportionally to the number of times a word appears in the document but is offset by the frequency of the word in the corpus. Variations of the tf-idf weighting scheme are often used by search engines as a central tool in scoring and ranking a document's relevance given a user query.
</p>
    
   <p>
One of the simplest ranking functions is computed by summing the tf-idf for each query term; many more sophisticated ranking functions are variants of this simple model.
</p>
    
   <p>
Tf-idf can be successfully used for stop-words filtering in various subject fields including text summarization and classification.
</p>
    
</font>

<font face='georgia'>
    <h4><strong>How to Compute:</strong></h4>

Typically, the tf-idf weight is composed by two terms: the first computes the normalized Term Frequency (TF), aka. the number of times a word appears in a document, divided by the total number of words in that document; the second term is the Inverse Document Frequency (IDF), computed as the logarithm of the number of the documents in the corpus divided by the number of documents where the specific term appears.

 <ul>
    <li>
<strong>TF:</strong> Term Frequency, which measures how frequently a term occurs in a document. Since every document is different in length, it is possible that a term would appear much more times in long documents than shorter ones. Thus, the term frequency is often divided by the document length (aka. the total number of terms in the document) as a way of normalization: <br>

$TF(t) = \frac{\text{Number of times term t appears in a document}}{\text{Total number of terms in the document}}.$
</li>
<li>
<strong>IDF:</strong> Inverse Document Frequency, which measures how important a term is. While computing TF, all terms are considered equally important. However it is known that certain terms, such as "is", "of", and "that", may appear a lot of times but have little importance. Thus we need to weigh down the frequent terms while scale up the rare ones, by computing the following: <br>

$IDF(t) = \log_{e}\frac{\text{Total  number of documents}} {\text{Number of documents with term t in it}}.$
for numerical stabiltiy we will be changing this formula little bit
$IDF(t) = \log_{e}\frac{\text{Total  number of documents}} {\text{Number of documents with term t in it}+1}.$
</li>
</ul>

<br>
<h4><strong>Example</strong></h4>
<p>

Consider a document containing 100 words wherein the word cat appears 3 times. The term frequency (i.e., tf) for cat is then (3 / 100) = 0.03. Now, assume we have 10 million documents and the word cat appears in one thousand of these. Then, the inverse document frequency (i.e., idf) is calculated as log(10,000,000 / 1,000) = 4. Thus, the Tf-idf weight is the product of these quantities: 0.03 * 4 = 0.12.
</p>
</font>

## Task-1

<font face='georgia'>
    <h4><strong>1. Build a TFIDF Vectorizer & compare its results with Sklearn:</strong></h4>

<ul>
    <li> As a part of this task you will be implementing TFIDF vectorizer on a collection of text documents.</li>
    <br>
    <li> You should compare the results of your own implementation of TFIDF vectorizer with that of sklearns implemenation TFIDF vectorizer.</li>
    <br>
    <li> Sklearn does few more tweaks in the implementation of its version of TFIDF vectorizer, so to replicate the exact results you would need to add following things to your custom implementation of tfidf vectorizer:
       <ol>
        <li> Sklearn has its vocabulary generated from idf sroted in alphabetical order</li>
        <li> Sklearn formula of idf is different from the standard textbook formula. Here the constant <strong>"1"</strong> is added to the numerator and denominator of the idf as if an extra document was seen containing every term in the collection exactly once, which prevents zero divisions.
            
 $IDF(t) = 1+\log_{e}\frac{1\text{ }+\text{ Total  number of documents in collection}} {1+\text{Number of documents with term t in it}}.$
        </li>
        <li> Sklearn applies L2-normalization on its output matrix.</li>
        <li> The final output of sklearn tfidf vectorizer is a sparse matrix.</li>
    </ol>
    <br>
    <li>Steps to approach this task:
    <ol>
        <li> You would have to write both fit and transform methods for your custom implementation of tfidf vectorizer.</li>
        <li> Print out the alphabetically sorted voacb after you fit your data and check if its the same as that of the feature names from sklearn tfidf vectorizer. </li>
        <li> Print out the idf values from your implementation and check if its the same as that of sklearns tfidf vectorizer idf values. </li>
        <li> Once you get your voacb and idf values to be same as that of sklearns implementation of tfidf vectorizer, proceed to the below steps. </li>
        <li> Make sure the output of your implementation is a sparse matrix. Before generating the final output, you need to normalize your sparse matrix using L2 normalization. You can refer to this link https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.normalize.html </li>
        <li> After completing the above steps, print the output of your custom implementation and compare it with sklearns implementation of tfidf vectorizer.</li>
        <li> To check the output of a single document in your collection of documents,  you can convert the sparse matrix related only to that document into dense matrix and print it.</li>
        </ol>
    </li>
    <br>
   </ul>

  <p> <font color="#e60000"><strong>Note-1: </strong></font> All the necessary outputs of sklearns tfidf vectorizer have been provided as reference in this notebook, you can compare your outputs as mentioned in the above steps, with these outputs.<br>
   <font color="#e60000"><strong>Note-2: </strong></font> The output of your custom implementation and that of sklearns implementation would match only with the collection of document strings provided to you as reference in this notebook. It would not match for strings that contain capital letters or punctuations, etc, because sklearn version of tfidf vectorizer deals with such strings in a different way. To know further details about how sklearn tfidf vectorizer works with such string, you can always refer to its official documentation.<br>
   <font color="#e60000"><strong>Note-3: </strong></font> During this task, it would be helpful for you to debug the code you write with print statements wherever necessary. But when you are finally submitting the assignment, make sure your code is readable and try not to print things which are not part of this task.
    </p>

### Corpus

In [2]:
## SkLearn# Collection of string documents

corpus = [
     'this is the first document',
     'this document is the second document',
     'and this is the third one',
     'is this the first document',
]

### SkLearn Implementation

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
vectorizer.fit(corpus)
skl_output = vectorizer.transform(corpus)

In [4]:
# sklearn feature names, they are sorted in alphabetic order by default.

print(vectorizer.get_feature_names())

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [5]:
# Here we will print the sklearn tfidf vectorizer idf values after applying the fit method
# After using the fit function on the corpus the vocab has 9 words in it, and each has its idf value.

print(vectorizer.idf_)

[1.91629073 1.22314355 1.51082562 1.         1.91629073 1.91629073
 1.         1.91629073 1.        ]


In [6]:
# shape of sklearn tfidf vectorizer output after applying transform method.

skl_output.shape

(4, 9)

In [7]:
# sklearn tfidf values for first line of the above corpus.
# Here the output is a sparse matrix

print(skl_output
      )

  (0, 8)	0.38408524091481483
  (0, 6)	0.38408524091481483
  (0, 3)	0.38408524091481483
  (0, 2)	0.5802858236844359
  (0, 1)	0.46979138557992045
  (1, 8)	0.281088674033753
  (1, 6)	0.281088674033753
  (1, 5)	0.5386476208856763
  (1, 3)	0.281088674033753
  (1, 1)	0.6876235979836938
  (2, 8)	0.267103787642168
  (2, 7)	0.511848512707169
  (2, 6)	0.267103787642168
  (2, 4)	0.511848512707169
  (2, 3)	0.267103787642168
  (2, 0)	0.511848512707169
  (3, 8)	0.38408524091481483
  (3, 6)	0.38408524091481483
  (3, 3)	0.38408524091481483
  (3, 2)	0.5802858236844359
  (3, 1)	0.46979138557992045


In [8]:
# sklearn tfidf values for first line of the above corpus.
# To understand the output better, here we are converting the sparse output matrix to dense matrix and printing it.
# Notice that this output is normalized using L2 normalization. sklearn does this by default.

print(skl_output[0].toarray())

[[0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]]


### Your custom implementation

In [9]:
# Write your code here.
# Make sure its well documented and readble with appropriate comments.
# Compare your results with the above sklearn tfidf vectorizer
# You are not supposed to use any other library apart from the ones given below

from collections import Counter
from tqdm import tqdm
from scipy.sparse import csr_matrix
import math
import operator
from sklearn.preprocessing import normalize
import numpy

def fit(corpus):
  unique_words = []
  if isinstance(corpus, list):
    for sent in corpus:
      for word in sent.split():
        if len(word) >= 2:
          if word not in unique_words:
            unique_words.append(word)
          else:
            continue
        else:
          continue
  unique_words.sort()

  return {word: index for index, word in enumerate(unique_words)}

vocab = fit(corpus)
print(vocab)


{'and': 0, 'document': 1, 'first': 2, 'is': 3, 'one': 4, 'second': 5, 'the': 6, 'third': 7, 'this': 8}


In [10]:
#idf value calculation
def idf(word_list, dataset):
  N = len(dataset)
  # to keep a counter for documents in which the unique number is present
  idf_value = dict()
  #print(list(word_list.keys()))
  for word in list(word_list.keys()):
    if len(word) < 2:
      continue 
    else:
      doc_count = 0
      for doc in dataset:
        if word in doc:
          doc_count += 1
      idf_value[word] = doc_count

  lst = [1 + math.log((N+1)/(idf_value+1)) for idf_value in idf_value.values()]
  return lst
  
print(idf(vocab, corpus))

[1.916290731874155, 1.2231435513142097, 1.5108256237659907, 1.0, 1.916290731874155, 1.916290731874155, 1.0, 1.916290731874155, 1.0]


In [11]:
# Term frequency calculation per review/doc in corpus 
def per_review_TF(dataset):
  main_list = []
  for doc in dataset:
    doc_dict = dict()
    for ele in fit(dataset).keys():
      doc_dict[ele] = 0
      for word in doc.split():
        if ele == word:
          doc_dict[ele] += 1   
       
    main_list.append(doc_dict)
  return main_list

print(per_review_TF(corpus))

[{'and': 0, 'document': 1, 'first': 1, 'is': 1, 'one': 0, 'second': 0, 'the': 1, 'third': 0, 'this': 1}, {'and': 0, 'document': 2, 'first': 0, 'is': 1, 'one': 0, 'second': 1, 'the': 1, 'third': 0, 'this': 1}, {'and': 1, 'document': 0, 'first': 0, 'is': 1, 'one': 1, 'second': 0, 'the': 1, 'third': 1, 'this': 1}, {'and': 0, 'document': 1, 'first': 1, 'is': 1, 'one': 0, 'second': 0, 'the': 1, 'third': 0, 'this': 1}]


In [26]:
# transform method
from sklearn.preprocessing import normalize
def transform(data_set, vocabulary):
  row_index = []
  column_index = []
  value = []
  lst = per_review_TF(data_set)
  final_lst = []
  for ele in list(enumerate(lst)):
    for count in list(enumerate(ele[1].values())):
      row_index.append(ele[0])
      column_index.append(count[0])
      tf_idf_value = count[1] * idf(vocabulary,data_set)[count[0]]
      value.append(tf_idf_value)

  #print(row_index)
  #print(column_index)
  #print(value)
  x = csr_matrix((value, (row_index, column_index)), shape = (len(data_set),len(vocabulary)))
  final = normalize(x, norm = 'l2')
  final.eliminate_zeros()

  return final
 
result = transform(corpus, vocab)
print(result)


  (0, 1)	0.46979138557992045
  (0, 2)	0.5802858236844359
  (0, 3)	0.38408524091481483
  (0, 6)	0.38408524091481483
  (0, 8)	0.38408524091481483
  (1, 1)	0.6876235979836938
  (1, 3)	0.281088674033753
  (1, 5)	0.5386476208856763
  (1, 6)	0.281088674033753
  (1, 8)	0.281088674033753
  (2, 0)	0.511848512707169
  (2, 3)	0.267103787642168
  (2, 4)	0.511848512707169
  (2, 6)	0.267103787642168
  (2, 7)	0.511848512707169
  (2, 8)	0.267103787642168
  (3, 1)	0.46979138557992045
  (3, 2)	0.5802858236844359
  (3, 3)	0.38408524091481483
  (3, 6)	0.38408524091481483
  (3, 8)	0.38408524091481483


In [27]:
# Dense matrix form
print(transform(corpus, vocab)[0].toarray())

[[0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]]


In [28]:
# Dense matrix form
print(transform(corpus, vocab).shape)

(4, 9)


## Task-2

<font face='georgia'>
    <h4><strong>2. Implement max features functionality:</strong></h4>

<ul>
    <li> As a part of this task you have to modify your fit and transform functions so that your vocab will contain only 50 terms with top idf scores.</li>
    <br>
    <li>This task is similar to your previous task, just that here your vocabulary is limited to only top 50 features names based on their idf values. Basically your output will have exactly 50 columns and the number of rows will depend on the number of documents you have in your corpus.</li>
    <br>
    <li>Here you will be give a pickle file, with file name <strong>cleaned_strings</strong>. You would have to load the corpus from this file and use it as input to your tfidf vectorizer.</li>
    <br>
    <li>Steps to approach this task:
    <ol>
        <li> You would have to write both fit and transform methods for your custom implementation of tfidf vectorizer, just like in the previous task. Additionally, here you have to limit the number of features generated to 50 as described above.</li>
        <li> Now sort your vocab based in descending order of idf values and print out the words in the sorted voacb after you fit your data. Here you should be getting only 50 terms in your vocab. And make sure to print idf values for each term in your vocab. </li>
        <li> Make sure the output of your implementation is a sparse matrix. Before generating the final output, you need to normalize your sparse matrix using L2 normalization. You can refer to this link https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.normalize.html </li>
        <li> Now check the output of a single document in your collection of documents,  you can convert the sparse matrix related only to that document into dense matrix and print it. And this dense matrix should contain 1 row and 50 columns. </li>
        </ol>
    </li>
    <br>
   </ul>

In [29]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [31]:
# Below is the code to load the cleaned_strings pickle file provided
# Here corpus is of list type

import pickle
with open('/content/drive/MyDrive/[5-Assignment] TFIDF vectorizer implementation files/cleaned_strings', 'rb') as f:
    corpus_1 = pickle.load(f)
    
# printing the length of the corpus loaded
print("Number of documents in corpus = ",len(corpus_1))

Number of documents in corpus =  746


In [32]:
# Write your code here.
# Try not to hardcode any values.
# Make sure its well documented and readble with appropriate comments.

from collections import Counter
from tqdm import tqdm
from scipy.sparse import csr_matrix
import math
import operator
from sklearn.preprocessing import normalize
import numpy

def fit(corpus):
  unique_words = []
  if isinstance(corpus, list):
    for sent in corpus:
      for word in sent.split():
        if len(word) >= 2:
          if word not in unique_words:
            unique_words.append(word)
          else:
            continue
        else:
          continue
  unique_words.sort()

  return {word: index for index, word in enumerate(unique_words)}

vocab_1 = fit(corpus_1)
print(len(vocab_1))

2886


In [33]:
#top 50 idf value calculation

def idf(word_list, dataset):
  N = len(dataset)
  # to keep a counter for documents in which the unique number is present
  idf_dict = dict()
  #print(list(word_list.keys()))
  for word in list(word_list.keys()):
    if len(word) < 2:
      continue 
    else:
      doc_count = 0
      for doc in dataset:
        if word in doc:
          doc_count += 1
      idf_dict[word] = doc_count

  lst = [1 + math.log((N+1)/(idf_value+1)) for idf_value in idf_dict.values()]
  lst_50 = sorted(lst,reverse = True)
  return lst_50[0:50]
  
print(idf(vocab_1, corpus_1))
print(len(idf(vocab_1, corpus_1)))

[6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872]
50


In [34]:
# Vocab with top 50 idf values

def idf(word_list, dataset):
  N = len(dataset)
  # to keep a counter for documents in which the unique number is present
  idf_dict = dict()
  #print(list(word_list.keys()))
  for word in list(word_list.keys()):
    if len(word) < 2:
      continue 
    else:
      doc_count = 0
      for doc in dataset:
        #print(doc)
        if word in doc.split():
          doc_count += 1
      idf_dict[word] = doc_count
  
  dct = dict()
  for idf_item in idf_dict.items():
    dct[idf_item[0]] = 1 + math.log((N+1)/(idf_item[1]+1))
  
  top_vocab = []
  for wrd in sorted(dct.items(), key = lambda x: x[1], reverse = True)[0:50]:
    top_vocab.append(wrd[0])
  
  return sorted(dct.items(), key = lambda x: x[1], reverse = True)[0:50]
  
print(idf(vocab_1, corpus_1))

[('aailiyah', 6.922918004572872), ('abandoned', 6.922918004572872), ('abroad', 6.922918004572872), ('abstruse', 6.922918004572872), ('academy', 6.922918004572872), ('accents', 6.922918004572872), ('accessible', 6.922918004572872), ('acclaimed', 6.922918004572872), ('accolades', 6.922918004572872), ('accurate', 6.922918004572872), ('accurately', 6.922918004572872), ('achille', 6.922918004572872), ('ackerman', 6.922918004572872), ('actions', 6.922918004572872), ('adams', 6.922918004572872), ('add', 6.922918004572872), ('added', 6.922918004572872), ('admins', 6.922918004572872), ('admiration', 6.922918004572872), ('admitted', 6.922918004572872), ('adrift', 6.922918004572872), ('adventure', 6.922918004572872), ('aesthetically', 6.922918004572872), ('affected', 6.922918004572872), ('affleck', 6.922918004572872), ('afternoon', 6.922918004572872), ('aged', 6.922918004572872), ('ages', 6.922918004572872), ('agree', 6.922918004572872), ('agreed', 6.922918004572872), ('aimless', 6.92291800457287

In [35]:
# Term frequency calculation per review/doc in corpus 

def per_review_TF(vocabulary ,dataset):
  main_list = []
  top_idf = idf(vocabulary, dataset)

  for document in dataset:
    doc_dictionary = dict()
    for element in top_idf:
      doc_dictionary[element[0]] = 0
      for wordd in document.split():
        if element[0] == wordd:
          doc_dictionary[element[0]] += 1   
       
    main_list.append(doc_dictionary)
  return main_list

print(per_review_TF(vocab_1, corpus_1))
print(len(per_review_TF(vocab_1, corpus_1)))


[{'aailiyah': 0, 'abandoned': 0, 'abroad': 0, 'abstruse': 0, 'academy': 0, 'accents': 0, 'accessible': 0, 'acclaimed': 0, 'accolades': 0, 'accurate': 0, 'accurately': 0, 'achille': 0, 'ackerman': 0, 'actions': 0, 'adams': 0, 'add': 0, 'added': 0, 'admins': 0, 'admiration': 0, 'admitted': 0, 'adrift': 0, 'adventure': 0, 'aesthetically': 0, 'affected': 0, 'affleck': 0, 'afternoon': 0, 'aged': 0, 'ages': 0, 'agree': 0, 'agreed': 0, 'aimless': 1, 'aired': 0, 'akasha': 0, 'akin': 0, 'alert': 0, 'alike': 0, 'allison': 0, 'allow': 0, 'allowing': 0, 'alongside': 0, 'amateurish': 0, 'amaze': 0, 'amazed': 0, 'amazingly': 0, 'amusing': 0, 'amust': 0, 'anatomist': 0, 'angel': 0, 'angela': 0, 'angelina': 0}, {'aailiyah': 0, 'abandoned': 0, 'abroad': 0, 'abstruse': 0, 'academy': 0, 'accents': 0, 'accessible': 0, 'acclaimed': 0, 'accolades': 0, 'accurate': 0, 'accurately': 0, 'achille': 0, 'ackerman': 0, 'actions': 0, 'adams': 0, 'add': 0, 'added': 0, 'admins': 0, 'admiration': 0, 'admitted': 0, 'adr

In [37]:
# transform method
from sklearn.preprocessing import normalize
def transform(data_set, vocabulary):
  row_index = []
  column_index = []
  value = []
  idf_value_1 = idf(vocabulary,data_set)
  lst_1 = per_review_TF(vocabulary, data_set)
  for ele in list(enumerate(lst_1)):
    
    for count in list(enumerate(ele[1].values())):
      row_index.append(ele[0])
      column_index.append(count[0])
      tf_idf_value_1 = count[1] * (idf_value_1[count[0]][1])
      value.append(tf_idf_value_1)

  #print(len(row_index))
  #print(len(column_index))
  #print(len(value))
  x = csr_matrix((value, (row_index, column_index)), shape = (len(data_set),len(idf_value_1) ) )
  final = normalize(x, norm = 'l2')
  final.eliminate_zeros()
  return final

print(transform(corpus_1, vocab_1))


  (0, 30)	1.0
  (68, 24)	1.0
  (72, 29)	1.0
  (74, 31)	1.0
  (119, 33)	1.0
  (135, 3)	0.37796447300922725
  (135, 10)	0.37796447300922725
  (135, 18)	0.37796447300922725
  (135, 20)	0.37796447300922725
  (135, 36)	0.37796447300922725
  (135, 40)	0.37796447300922725
  (135, 41)	0.37796447300922725
  (176, 49)	1.0
  (181, 13)	1.0
  (192, 21)	1.0
  (193, 23)	1.0
  (216, 2)	1.0
  (222, 47)	1.0
  (225, 19)	1.0
  (227, 17)	1.0
  (241, 44)	1.0
  (270, 1)	1.0
  (290, 25)	1.0
  (333, 26)	1.0
  (334, 15)	1.0
  (341, 43)	1.0
  (344, 42)	1.0
  (348, 8)	1.0
  (377, 37)	1.0
  (409, 5)	1.0
  (430, 39)	1.0
  (457, 45)	1.0
  (461, 4)	1.0
  (465, 38)	1.0
  (475, 35)	1.0
  (493, 6)	1.0
  (500, 48)	1.0
  (548, 0)	0.7071067811865476
  (548, 32)	0.7071067811865476
  (608, 14)	1.0
  (612, 11)	1.0
  (620, 46)	1.0
  (632, 7)	1.0
  (644, 12)	0.7071067811865476
  (644, 27)	0.7071067811865476
  (664, 28)	1.0
  (667, 22)	1.0
  (691, 34)	1.0
  (697, 9)	1.0
  (722, 16)	1.0


In [38]:
# Dense matrix form
print(transform(corpus_1, vocab_1).toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [39]:
# Dense matrix form
print(transform(corpus_1, vocab_1).shape)

(746, 50)
